### ISSUE TITLE
ModuleNotFoundError: No module named 'pyrogram.api'

### ISSUE THREAD

**Issue by ghost** [gurland/telegram-delete-all-messages#18]
Python 3.8.6, all is made as specified in readme.

**Comment by HawkeyePierce89** [comment]
https://github.com/gurland/telegram-delete-all-messages/pull/17

**Comment by ShowStopperTheSecond** [comment]
use pyrogram 0.18.0  it worked for me

**Comment by gurland** [comment]
Thanks for your report! Fixed in  #17 PR.
