### ISSUE TITLE
ModuleNotFoundError: No module named 'pyrogram.api'

### ISSUE THREAD

**Issue by kgggggb** [gurland/telegram-delete-all-messages#19]
![111](https://user-images.githubusercontent.com/47137779/98451066-5b38a680-217d-11eb-9a75-54fd352beac1.png)
![222](https://user-images.githubusercontent.com/47137779/98451067-5ecc2d80-217d-11eb-815b-98a9fa157e93.png)

**Comment by SoHardDay** [comment]
https://github.com/gurland/telegram-delete-all-messages/pull/17

**Comment by gurland** [comment]
Thanks for your report! Fixed in  #17 PR.
