### ISSUE TITLE
Delete messages in normal groups?

### ISSUE THREAD

**Issue by jarrah31** [gurland/telegram-delete-all-messages#2]
Just wondering if it's possible to delete messages in a normal group please?

i.e. could chat.type be modified to look for another type of group, and if so do you know what other types there are please?

**Comment by jarrah31** [comment]
I've figured it out - the groups types I've found so far are:

bot
group
private

**Comment by theatischbein** [comment]
I fixed it for `group` in https://github.com/gurland/telegram-delete-all-messages/pull/7
