### ISSUE TITLE
FIX - flood warning

### ISSUE THREAD

**Issue by SiNaPsEr0x** [gurland/telegram-delete-all-messages#21]
for fix this error:

pyrogram.errors.exceptions.flood_420.FloodWait: [420 FLOOD_WAIT_X]: A wait of 21 seconds is required (caused by "messages.Search")

do you change number of count from 100 tu 1000

```
for i in range(0, messages_count, 1000):
                q = self.search_messages()
                self.update_ids(q)
                self.add_offset += 1000
```

**Comment by gurland** [comment]
Thanks, fixed in  #17 PR.
