### ISSUE TITLE
"pyrogram.errors.exceptions.flood_420.FloodWait" when searching for messages, needs sleep_threshold set

### ISSUE THREAD

**Issue by ultradumb** [gurland/telegram-delete-all-messages#25]
I believe, sleep_threshold parameter should be added to app.send() method when searching messages, otherwise it dies sometimes with "pyrogram.errors.exceptions.flood_420.FloodWait". Value of 60 seconds seems to work OK.
test results:
[Q]
Found 40835 your messages in selected supergroup
[client] Sleeping for 15s (required by "messages.Search")
[client] Sleeping for 9s (required by "messages.Search")
[client] Sleeping for 3s (required by "messages.Search")
[client] Sleeping for 9s (required by "messages.Search")
Searching messages. OFFSET: 40900
[UQ]

**Comment by gurland** [comment]
Thank you for your suggestion, added sleep_threshold in #35 .

**Comment by hesoyamfaky** [comment]
Здравствуйте, можно пример
