### ISSUE TITLE
Not starting

### ISSUE THREAD

**Issue by HeroHann** [gurland/telegram-delete-all-messages#28]
Getting this error:
Traceback (most recent call last):
  File "/Users/bm/telegram-delete-all-messages/cleaner.py", line 5, in <module>
    from pyrogram.api.functions.messages import Search
ModuleNotFoundError: No module named 'pyrogram.api'

**Comment by HeroHann** [comment]
Package    Version
---------- -------
async-lru  1.0.2
pip        20.3.1
pyaes      1.6.1
pyasn1     0.4.8
Pyrogram   1.1.13
PySocks    1.7.1
rsa        4.7
setuptools 51.0.0
Telethon   1.19.2
TgCrypto   1.2.2
wheel      0.36.1

**Comment by gurland** [comment]
@HeroHann Could you please provide output of  `git remote show origin` here?

**Comment by hannesveit** [comment]
Probably pulled from borontov rather than gurland. BTW I have a PR open that fixes the clone URL in the README, among other improvements: https://github.com/gurland/telegram-delete-all-messages/pull/29

@HeroHann:
```bash
git clone https://github.com/gurland/telegram-delete-all-messages.git
```

**Comment by HeroHann** [comment]
Yeah the new git clone helped.

When started through terminal I get this:
  File "cleaner.py", line 53
    print('\n'.join((f'{i}. {name.capitalize()}' for i, name in group_types.items())))
                                               ^
SyntaxError: invalid syntax

When opening the py file and running it directly it works.

**Comment by gurland** [comment]
Great to hear that issues is resolved. #29 will fix incorrect git repository link inside `README.md`
