### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by timea-techgirl** [gurland/telegram-delete-all-messages#3]
In my telegram chat export, I have all the groups I ever joined, I have no messages in the groups except "xxx joined". I'm unable to delete these messages directly. They appear in the chat export. I want these groups gone. I just want to delete these kind of messages.
Can I remove these joined messages from groups even if I'm not the admin with your tool?

**Comment by borontov** [comment]
No, you cannot do this even in the original client.

But you can write a script to remove these messages from the chat export file.

**Comment by timea-techgirl** [comment]
Oh I see. Thanks for the response. :)
