### ISSUE TITLE
Program continuously sleeping, doesn't work properly

### ISSUE THREAD

**Issue by erbanku** [gurland/telegram-delete-all-messages#40]
### I am not sure if this is a problem on Telegram API side, below are the error message & screenshot, please help, thanks.

> # [client] Sleeping for 24s (required by "messages.GetDialogs")
![image](https://user-images.githubusercontent.com/79493862/131658730-100e015c-85d2-44f2-94f5-3890998f0090.png)

**Comment by xanoni** [comment]
Ack, same problem.
