### ISSUE TITLE
[Feature Request] Delete messages in every group

### ISSUE THREAD

**Issue by ixearth** [gurland/telegram-delete-all-messages#5]
I have joined lots of chats, so instead of deleting messages of groups one by one, I want to delete all of them at once.

Currently I run a bash shell loop to run the script, but the group number seems changes sometimes. so there are chance that I didn't delete messages in some groups.

Could you add an argument that specific something like `-all` for this? or answer `ALL` to delete messages in every group?

Some groups are not listed (seems happens when there are too many chats, I got these groups listed by quitting some groups and channels), I want to delete all of messages in every group I joined. To delete them I have to send new messages in these groups and then the python script will list it.
Seems it only list 50 groups at most.
Is it possible to find out all of groups I joined and delete them at once?

**Comment by gurland** [comment]
Thanks for your report. I have divided this issue into 3 separate:
#10 - remove dialogs limit
#11 - improve CLI by adding command-line arguments
#12 - feature to delete messages everywhere.

@ixearth would you like to see message deletion in groups/supergroups only or maybe personal chats/channels posts?

**Comment by ixearth** [comment]
@gurland I would recommend to add multiple command-line arguments such like

`-type group supergroup -id <some-chat-id> <some-other-chat-id>`

The value of `-type` can be `private`, `group`, `supergroup` or `channel`, the id can be chat id of any of them (the one need to add quote characters when the id was negative number). Users should also be able to get chat IDs by using the script.

btw is "Saved Message" also being considered as personal chat? If it is then maybe it should be noted in the help message to avoid data loss. the one may don't think "Saved Message" as any of that four chat type. (you may add the dialogue to ask user to type `yes` to confirm, it won't be a problem if the one could run it as `yes | cleaner.py` when he needs to run it in non-interactive mode)

The reason I need to delete all of my chat message is I want to delete them before I delete my account, this use case is very rare, so I think `-type` is enough for such needs and `-all` is not necessary.

I need to delete messages from certain groups and private chats every period of time, so `-id` would be much useful for me to run the script with crontab.
