### ISSUE TITLE
[bug] update pyrogram

### ISSUE THREAD

**Issue by PaSSw0rds** [gurland/telegram-delete-all-messages#50]
pyrogram.errors.exceptions.not_acceptable_406.NotAcceptable: [406 Not Acceptable]: [406 UPDATE_APP_TO_LOGIN] (caused by "auth.SendCode")

**Comment by gurland** [comment]
Remove `venv` directory and re-run installation script. That should install `pyrogram==1.2.11` which fixes the problem.
