### ISSUE TITLE
Syntax error line 72   print(f'  {i+1}. {group.title}')

### ISSUE THREAD

**Issue by AliJamaleddine** [gurland/telegram-delete-all-messages#59]
Hello I'm having this error when I try to execute the script, any solutions ? 

 File "cleaner.py", line 72
    print(f'  {i+1}. {group.title}')
                                  ^
SyntaxError: invalid syntax

**Comment by whelpy** [comment]
use python 3.6 or newer

**Comment by gurland** [comment]
Hello @AliJamaleddine, F-strings are a feature introduced in Python 3.6 that allow for string interpolation, making it easier to embed expressions inside string literals for formatting. F-string is being used in a line you have sent, therefore, please, install Python 3.6 or newer.
