### ISSUE TITLE
can't find supergroup when it's pined to top

### ISSUE THREAD

**Issue by 0312birdzhang** [gurland/telegram-delete-all-messages#6]

**Comment by vtronko** [comment]
Yeah, spotted the same bug.

**Comment by vtronko** [comment]
It's probably an upstream bug, I think

**Comment by vtronko** [comment]
https://github.com/pyrogram/pyrogram/pull/427

**Comment by gurland** [comment]
Thanks for reporting, fixed your issue.

**Comment by vtronko** [comment]
@gurland I filed a PR upstream, issuing same request two times does not seem cool.
