### ISSUE TITLE
It used to run the script very well, but in the last few days it reported the following error:

### ISSUE THREAD

**Issue by data7799** [gurland/telegram-delete-all-messages#62]
It used to run the script very well, but in the last few days it reported the following error:
![tg1](https://github.com/gurland/telegram-delete-all-messages/assets/15697784/04542257-be6d-4aba-b92e-da1495856dd3)
What should I do with it?

**Comment by data7799** [comment]
I tried to synchronize the system time, but it didn't work

**Comment by kiwioverflow** [comment]
I have same issue.

There is no problem with the system time, and when a new session is authenticated, it works normally for the first time, but after the program is turned off, it does not work again until get a new session.

**Comment by FFFcat** [comment]
Update pyrogram version can resolve. I have updated to my repository.

**Comment by data7799** [comment]
> Update pyrogram version can resolve. I have updated to my repository.
Thank you,it works!

**Comment by vertin2** [comment]
I dont understand, how do you fix this? I am getting same problem. I got it to run once on windows 10 but now it wont

**Comment by data7799** [comment]
> I dont understand, how do you fix this? I am getting same problem. I got it to run once on windows 10 but now it wont

I deleted the script and used the script modified by FFFcat upstairs.
